version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: biblioteca-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - biblioteca-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/biblioteca-iepmm
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=sua_chave_secreta_aqui
    depends_on:
      - mongodb
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local