version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: biblioteca-mongodb-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - biblioteca-network-dev

networks:
  biblioteca-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
    driver: local